travis:
  secure:
    BINSTAR_TOKEN: mlnlU86LFMn9sQYyvHjqwMdKsi3IQn/KkMNWBwoDqbDq+SL+3nVfKn7zxOBF7UF7YRlLNhj/m4YyZQuib6TNiOfrK/0tzf7gxbz4C2Nc9h1iDABOswGLo5vv023qT4m3bgH76eSjG2tZspWfzmKESoQRhNwXtPWS6va78z/rDolXOJ11FiTduOHf8RNEfYsaKYCxOAGqVroCfteuBzlKmzAccgoCm999yfaAYweO0keqaX4oHABD/0i0bCOdNJ5AlHpr508+129AsBjYoXdRm6e6gxM15DQm7M7DyeJSEHtmsmjZfgjuSGa6PU2TeoyKT9MzMW1Ri1200rTRvF1FQpSWOFar/SlCpycY09m9z+yc12iG1IMdVB577wIGlqkh8H6MbSRTEP0XKg43VSp2zzi3+A1NW54TkLk1cmf5UKwyCPK5gkYMViHVKosDuVg7gn29pOqCT/E9apY5s3/TMw4ZMWXmfTKqj+bmhjWggjgCwOZi//ZUt6U7Ho5nvD6xAbKVkpzEhF3hVd2kKwzc4+0lI00uQkkmNfYl+EvPRqjfyJVhwNXtG2KT+YmLkqFIIl3PQXLFNMRBOlpyCNV72ULDsg5eXv9ZIOwtrfo91tE8qlNxxNQ1Dt+YkcDMG4F97q06iDPM53XLP9uQkUg8mBFkWY+5Jd5DmqwroACF6BA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
